### ISSUE TITLE
[Question] Do you know if it's possible to pull and handle comments held for review?

### ISSUE THREAD

**Issue by jayhorowitz** [mattwright324/youtube-comment-suite#12]
YouTube allows users to set up comment filters and/or to enable YouTube's comment filtering. This "holds for review" all comments that (a) meet filter criteria or (b) are determined by YouTube to be potentially inappropriate. YouTube separately filters - and holds for review - comments that it deems potentially spam.

Unfortunately / fortunately, my channel is at the point that I can't manage those comments using YouTube's interface. There are thousands of comments held for review every day and YouTube's comment management system royally sucks at bulk actions. (Like, trying to approve more than a dozen comments at once is hit-or-miss.)

Does the API allow for* the integration of comment review and approval / denial into YouTube Comment Suite?

Regardless, thank you for making this program. It's great, and was well worth the time it took me to figure out how to install and use Java8 on my MacBook Pro yesterday.

*I know that there's a big difference between "possible" and "you're going to do it."

**Comment by mattwright324** [comment]
This does appear to be possible after some research. You can retrieve comments that are held for review with `commentThreads.list` and using the `moderationStatus` parameter [here](https://developers.google.com/youtube/v3/docs/commentThreads/list#moderationStatus). You can then set the moderation status for these comments via `comments.setModerationStatus` [here](https://developers.google.com/youtube/v3/docs/comments/setModerationStatus).

This would be a difficult one for me to implement though as I have not dealt with comments on the YouTube site as I am not a creator and not too sure what the current implementation they have looks like. I don't currently have a channel with comments held for review to experiment with; either collaboration with someone who does or I would need to create dummy accounts to setup this situation.

I do think this is a good idea and something I will need to think about the best way to implement. Also thanks and I'm glad you find the program worthwhile to use!

**Comment by mattwright324** [comment]
> This would be a difficult one for me to implement though as I have not dealt with comments on the YouTube site as I am not a creator and not too sure what the current implementation they have looks like. I don't currently have a channel with comments held for review to experiment with; either collaboration with someone who does or I would need to create dummy accounts to setup this situation.

I take this statement back, as my machine is capable, I was able to create a short test video of YCS to use for testing as a creator and [uploaded it here](https://www.youtube.com/watch?v=eO4FYxeYH9Q). I set the video to have comments held for review for this situation and am more likely to investigate this as a feature.

**Comment by SiliconWafer** [comment]
Think there's any chance of this happening? :-)

It's not much, but I'll pay $250 for a working integration of 'held for review' and 'held as spam' comments in YCS! I can also help you test it if that would be useful.

**Comment by mattwright324** [comment]
Sure! 

To note, this project is not abandoned and I do check it regularly... I just get burned out quicker on larger changes to this app as I'm working full time. Also, this is why I've mostly focused on my smaller and less complicated projects (e.g. youtube-geofind, youtube-metadata, jports, bad-ui) as of late. This would likely be a larger change touching the ui, refresh process, and database -- I don't think I currently do anything special for refresh items that match accounts signed into the app which I would need to do here. 

I would likely need your assistance in testing and while I did make that video to play with, the volume of held for review and spam comments would be difficult to reproduce for testing on my own.

For better coordination, you can reach me at mattwright324@gmail.com

**Comment by mattwright324** [comment]
I have a version of this that can grab held-for-review and likely-spam comments from videos owned by signed-in accounts out in the `develop` branch and will be out in the next release.
