### ISSUE TITLE
Can't export because hard-coded to Windows/System32 which needs uber-permissions

### ISSUE THREAD

**Issue by AaronStew** [mattwright324/youtube-comment-suite#132]
Hi Matt - 

Your utility is great and still very usable.  But a huge frustration is that I can't save any results.  The "Export" feature immediately fails because it can't find or create a folder in C:\Windows\System32.  I can't create anything there either without very risky Permissions changes.

I also can't just Ctrl-A and select all comments because that either gets the comments without dates, or dates without comments etc.

Capturing the scrolling window has so far failed with all apps made for that.

So:  Please either let us specify an export folder or just change the hardwired location to eg. C:\Temp.

Thank you!

**Comment by mattwright324** [comment]
Hi @AaronStew 

Could you send a more detailed error or exception message? The application shouldn't be looking at or trying to create anything in System32, I assume something else is the cause. Export should create folders/files next to the jar in the folder you have it stored.

**Comment by AaronStew** [comment]
Thanks for the reply!  I attach two screenshots of the Export process I see; links below.

More info:  I'm on Windows 10 x64.  After a Java update my original Comment Suite installation would no longer start so I'm running YTCS via an elevated command line:

"C:\Program Files (x86)\Java\jre-1.8\bin\javaw.exe" -jar "D:\_Net\Youtube Comment Suite_p\youtube-comment-suite-1.4.8.jar"

Maybe that is contributing to my issue... never considered it.  I suppose I can reinstall YTCS if you think it might help.  I don't remember if that was simple for me or not; just that once I got it running I didn't want to change too much.

![CAP_ 39084](https://github.com/user-attachments/assets/60e2b5aa-d77b-41d6-b250-de4ff24573f1)
![CAP_ 39085](https://github.com/user-attachments/assets/d0da1b91-f0aa-41a8-b5da-f717207731df)

**Comment by AaronStew** [comment]
[I edited my post of a few minutes ago, to mention Windows Explorer involvement.]

**Comment by mattwright324** [comment]
Definitely has to be something with the way you are running the jar. I'm not sure if it will help much but potentially something with the `-Duser.dir` awg with a value of the app's folder could help or see if anything is weird if you use that JRE version and look at the values of `java.exe -XshowSettings:all`

**Comment by AaronStew** [comment]
Success.  In my elevated command window I navigated to C:\Temp and executed the command line (shown earlier) from there.  YTCS started up and worked normally, and Export now works fine, saving the CSV file to C:\Temp\2024.08.23 11.56.46.

Originally, above, my command window was in C:\Windows\System32 only by chance.  Running the JAR from there caused the problem.

Reinstalling YTCS would probably also have fixed it; though as noted that may need to be done after each Java update.

Thanks very much for this great app and for taking the time now to address my question.
