### ISSUE TITLE
[Request] Bulk add to group

### ISSUE THREAD

**Issue by Flashtrax** [mattwright324/youtube-comment-suite#16]
Ability to add a list of urls to a group would be very helpful.

**Comment by mattwright324** [comment]
This should be pretty simple to add in. I'll look into this, thanks!

**Comment by mattwright324** [comment]
This feature has been added in 3ba57a0c5dbda39ec87bec47ec28232e2caa00d9 on the replace-ytapi branch. It will be in the next release.

![](https://i.imgur.com/txxoVFE.png)

**Comment by Flashtrax** [comment]
Thank you!!!
