### ISSUE TITLE
Export Comments Language support

### ISSUE THREAD

**Issue by rokkyboy** [mattwright324/youtube-comment-suite#24]
Hello,

Thank you very much for your work on this project. I code as a hobby and was looking for an easy way to aggregate and analyze comments. This seemed perfect.

Unfortunately, the comments export function to JSON does not seem to support Korean. Perhaps the format is not UTF-8?

I've attached how it looks in Visual Studio Code. Korean shows up fine in the interface itself.
![Cap 2019-08-26 09-46-30-181](https://user-images.githubusercontent.com/8150021/63658565-64db2600-c7e6-11e9-92ef-e6a766e43b03.png)

![Cap 2019-08-26 09-44-25-732](https://user-images.githubusercontent.com/8150021/63658516-234a7b00-c7e6-11e9-81bf-af76391287d8.png)

**Comment by mattwright324** [comment]
Hi rokkyboy,

Thanks!

It appears that I am not explicitly writing the files as UTF-8 so the FileWriter uses the default encoding. It is curious that it displays correctly in the interface. Would you mind sharing your default encoding and OS? To find your default encoding quickly, you can run `java -XshowSettings` in your system console and it will be listed as `file.encoding` near the top.

I should hopefully be able to fix this by making it explicitly write the files as UTF-8.

**Comment by rokkyboy** [comment]
Hello!

Thanks for the quick response.

I am using Windows 10 Pro in Korean. Here is the default encoding per your
instruction:

[image: image.png]

Thanks!

Rok

**Comment by mattwright324** [comment]
It looks like you tried to attach a screenshot but I'm just seeing `[image: image.png]` as text

**Comment by rokkyboy** [comment]
Ooops

Here it is:

    file.encoding = MS949
    file.encoding.pkg = sun.io
    file.separator = \

**Comment by rokkyboy** [comment]
Hey Matt,

Sorry for the late reply. I just checked in Visual Studio Code with
different encoding, and it worked with Korean, not UTF-8. Here is a
screenshot. I should have thought to try diff encoding, but did not.

Thanks!


[image: image.png]


[image: image.png]

**Comment by rokkyboy** [comment]
Hey Matt,

A different question... do you plan on creating the option to:

1. export out to CSV
2. export in single file

Thanks :)

**Comment by rokkyboy** [comment]
Hey Matt!

Just another suggestion.. my goal was to use Power BI to analyze
youtube-comments. Unfortunately PowerBI doesn't seem to work with the
EUC-KR format, even when I change the encoding to Korean in Power BI.
Copying the JSON file to a new JSON file and saving it in UTF-8 format was
a work-around.

I think it would be great if the export format could be changed to UTF-8.

Thanks!

Rok

**Comment by mattwright324** [comment]
I am able to make export explicitly write files as UTF-8 and will do that.

I hadn't thought of CSV as an export option but it's something I will think about.

**Comment by mattwright324** [comment]
I am hoping that it will now write all files as UTF8 explicitly. I'll have this out in the next release.

**Comment by Rupthya** [comment]
I still have same issue exactly like this one,

file.encoding = MS950 (Traditional Chinese)

Export comment like Korean or Japanese all become Garbled, I'm using YouTube Comment Suite v1.4.3 and open the json file with Notepad++.

Thanks for your help.

**Comment by Rupthya** [comment]
> I am hoping that it will now write all files as UTF8 explicitly. I'll have this out in the next release.

I still have same issue exactly like this one,

file.encoding = MS950 (Traditional Chinese)

Export comment like Korean or Japanese all become Garbled, I'm using YouTube Comment Suite v1.4.3 and open the json file with Notepad++.

Thanks for your help.
