### ISSUE TITLE
Grabbing Video Data (FATAL)

### ISSUE THREAD

**Issue by Edenpac** [mattwright324/youtube-comment-suite#25]
I am using English Windows 10 Home. When I refresh, to download new comments, in the middle of grabbing, error comes out: "Grabbing Video Data (FATAL)".  I attached log file.
[output-20190826.log](https://github.com/mattwright324/youtube-comment-suite/files/3542237/output-20190826.log)

**Comment by mattwright324** [comment]
Thanks for reporting this, the issue appears to be that I didn't account for videos that have their view counts disabled which would be these ones from the log file you attached.
- https://youtu.be/QNVb3EfjIvA
- https://youtu.be/TvuUSxzpHlM
- https://youtu.be/oZT4k0Ti8Mc
- https://youtu.be/p2lTBQcT5pY

This is now fixed and will default the value to 0 when view count has been disabled. I was already doing this for likes/dislikes and comments which can be disabled too but didn't realize the view count could be too.
