### ISSUE TITLE
Sort channels alphabetically

### ISSUE THREAD

**Issue by sideloading** [mattwright324/youtube-comment-suite#28]
Hi,

Thanks for your efforts with this tool, it works great!

I was wondering if it's possible to add sorting by alphabetical order? Currently it seems to be in the order of when you add the channels, so it can be quite difficult to sort through to find the channel you want.

Example:

![manage groups](https://i.imgur.com/63R7tpW.png)
![search comments](https://i.imgur.com/ieNEKRE.png)

Thanks!

**Comment by mattwright324** [comment]
Thanks!

Yes, this will be easy to do.

**Comment by DontBLB** [comment]
Is it possible to load in the channel names after doing a quick add? (right now some appear with the names, others with the channel ID)? Or add some sort of search function within the group? Thanks :)
