### ISSUE TITLE
New version not running on ubuntu 16.04

### ISSUE THREAD

**Issue by KDE5FAN** [mattwright324/youtube-comment-suite#29]
Greetings from Lancaster!
I'm new to Github so all this is new to me but have been running ubuntu for 9+ years.  I went through your directions, and checked the java versions, and it said they were installed, but I ran the "apt install" again, and it said they were already installed.  I extracted the zip and tried running the youtube-comment-suite-1.4.2.jar and it said 
youtube-comment-suite-1.4.2.jar: command not found

I tried a few options:
**User@computer:~/temp/youtube-suite$  .youtube-comment-suite-1.4.2.jar**
.youtube-comment-suite-1.4.2.jar: command not found

**User@computer:~/temp/youtube-suite$  ./youtube-comment-suite-1.4.2.jar**
invalid file (bad magic number): Exec format error

**User@computer:~/temp/youtube-suite$  java -jar youtube-comment-suite-1.4.2.jar**
Error: Could not find or load main class jar

**User@computer:~/temp/youtube-suite$  sudo java -jar youtube-comment-suite-1.4.2.jar**
Error: Could not find or load main class io.mattw.youtube.commentsuite.FXMLSuite

**User@computer:~/temp/youtube-suite$  sudo java -jar ./youtube-comment-suite-1.4.2.jar**
Error: Could not find or load main class io.mattw.youtube.commentsuite.FXMLSuite

I also did a change mod to 722, 755 and 777 but still none of these worked.  Do you have any suggestions?

**Comment by mattwright324** [comment]
I have found trying to get Java / JavaFX applications to run in Ubuntu a bit tricky and the different java versions installed depending on the OS version is also tricky. My current instructions are applicable for Ubuntu 19. At some point I think they were applicable for either 16 or 18 but I had updated them because they stopped working.

In the past you used to be able to just do `sudo apt install default-jre openjfx` for both Java 8 and JavaFX 8. I would assume trying to install these on Ubuntu 16 would install newer versions than 8 but I'm not certain.

You could also look into trying to install Oracle JDK 8, I have done this before but don't have a guide handy currently.

**Comment by KDE5FAN** [comment]
Thanks. I'll do an install of 19 on a VM and give it a try on that as I wanted to try 19 anyway.  I'll report back if it works fine in 19 and I'll see what I can do to get it working in 16 and report on that as well. 

Also, IDK if there is a way I can contact you outside of this platform or privately on this platform (I'm new to github), after looking at your previous/current projects I think you may be interested in a couple project Idea's I've had for some time, so I'd like to privately contact you if possible.   It looks like we are fairly close to each other, I'm wondering if you ever go to the CPLUG meetings in Hburg (central penn Linux user group)?

**Comment by mattwright324** [comment]
Have you had any progress here?

I have not heard of or been to CPLUG before but see they have [a website](http://cplug.net/), sounds interesting. If you'd like you could reach me via email mattwright324@gmail.com

**Comment by mattwright324** [comment]
I've recently created a wiki page with instructions on how to get the app running in a variety of Ubuntu versions here.

* [Installation Ubuntu 16 17 18 19 20](https://github.com/mattwright324/youtube-comment-suite/wiki/Installation---Ubuntu-16-17-18-19-20)

I'll close this issue now, let me know if you have any problems.
