### ISSUE TITLE
problems with installing compiled jar in latest release

### ISSUE THREAD

**Issue by malagala** [mattwright324/youtube-comment-suite#3]
Hi,

I have downloaded and extracted the v.1.3.0 zip file given [here](https://github.com/mattwright324/youtube-comment-suite/releases/tag/v1.3.0) and have attempted to install the .jar file it contains by running:

`java -jar youtube-comment-suite.jar`

However, this only returns the following error:

`Could not find or load main class mattw.youtube.commentsuite.CommentSuite`

Do you know what could be going wrong? Are there other files I need to download? For context, I am using Ubuntu 16.04

Thanks

**Comment by mattwright324** [comment]
Hi malagala,

I had tested in my Ubuntu 16.04 environment but was successful in running the compiled jar. I think that the java version could be the culprit -- OpenJDK vs Oracle Java. Could you type `java -version` in the console and reply back with what it tells you?

**Comment by malagala** [comment]
`openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)`

**Comment by mattwright324** [comment]
I have tracked [down the issue](https://stackoverflow.com/a/40283931/2650847). OpenJDK oddly does not support JavaFX even though it's now a standard in Java 8. YCS is based in JavaFX. You will have to [replace your OpenJDK with OracleJDK](https://thishosting.rocks/install-java-ubuntu/). Scroll down to the Oracle Java tutorial. Please let me know it works out.

**Comment by mattwright324** [comment]
I found another and [simpler solution](https://stackoverflow.com/a/43301246/2650847). However, my Ubuntu environment has Oracle Java so I have not tested it. You can run `sudo apt-get install openjfx` to install the missing JavaFX libraries in OpenJDK on Ubuntu. Let me know which you try and how it works out.

**Comment by malagala** [comment]
yep your first solution worked! thanks so much

**Comment by mattwright324** [comment]
Great!
