### ISSUE TITLE
Error: Could not find or load main class

### ISSUE THREAD

**Issue by Edenpac** [mattwright324/youtube-comment-suite#32]
I tried to run last release of application. But it did not run. After running from CMD it shows error: Error: Could not find or load main class io.mattw.youtube.commentsuite.FXMLSuite. What could cause that?

**Comment by mattwright324** [comment]
Could you provide some more details? What OS are you running? What version on Java do you have installed?

**Comment by Edenpac** [comment]
I am running win10-64bit. I installed java version 11.0.5

**Comment by mattwright324** [comment]
That would be the problem, this application currently isn't compatible with Java 11 and beyond because JavaFX was decoupled (no longer included by default). You can try installing the [Java 8 from here](https://www.java.com/en/download/win10.jsp).

**Comment by Edenpac** [comment]
That worked! Thanks!

**Comment by mattwright324** [comment]
Great!
