### ISSUE TITLE
Import comments and channels

### ISSUE THREAD

**Issue by Edenpac** [mattwright324/youtube-comment-suite#34]
Hi, since you updating this app, would be possible to make action to import groups, channels and comments from any previous version?

**Comment by mattwright324** [comment]
Assuming you are coming from an older v1.4.x version of the app you could do the following.

From the old version, copy the files `commensuite.json` and `commentsuite.sqlite3` and paste them into folder of the newer version. 

These files store application settings (json) and the actual data (sqlite3), any `v1.4.x` version of these files will be compatible with the other `v1.4.x` versions of the app.

**Comment by Edenpac** [comment]
Ok, thanks :)
