### ISSUE TITLE
Export comments

### ISSUE THREAD

**Issue by John9593** [mattwright324/youtube-comment-suite#35]
Is it possible for you to add a way to export comments into a single file, this way I could take it for use in excel or other programs. Trying to combine thousands of .jsons is a bit too difficult

Either into a single .csv or a .json would be great or just some other way which would do the same trick

**Comment by mattwright324** [comment]
Technically they are all in a single file in the sqlite3 database.

**Comment by John9593** [comment]
Okay thanks, I've tried opening that file but can't get it to work properly with excel etc. Is there an easy way you could please tell me how to do so?

**Comment by John9593** [comment]
I've managed to open the SQLlite file, thanks for that. I can see several sections such as 'channels', 'comments' and several 'gitem...' - under the comments it displays a column with the channel ID - is there a way to get the channel name to show up also?

**Comment by mattwright324** [comment]
Though this isn't perfect because you need to know some sql and would have to recreate any search criteria to filter down if you had any. To use the channel ID to get the name you would have to do a JOIN on your select with the channels table.

**Comment by mattwright324** [comment]
It may make sense then to add some implementation that exports to a single file.

**Comment by John9593** [comment]
Okay thank you, I'll look into how to join with SQL. I can probably use the YouTube API to gather the channel names via the ID if I don't have any success.

**Comment by mattwright324** [comment]
SELECT * FROM comments LEFT JOIN USING (channel_id)

Might be able to use [SQLiteStudio](https://sqlitestudio.pl/) if that isn't what you are using already.

**Comment by John9593** [comment]
Concidently I am using SQLiteStudio, I tried to do that, but I couldn't get it to work (zero experience with this sort of stuff)... not to worry though, its not a big deal. Appreciate your time and thank you again.

**Comment by ThorThundera** [comment]
can you make a pdf export with beautiful format? thanks.

**Comment by mattwright324** [comment]
I've got a functional version of CSV export and comments in a single file both in commit 463b1c22a88a781d7d5b12b4473c18c848497f68. Videos will always be in a single file now too, no more single `meta` files. It will be out in the next release.

Examples with a group with 477,000 comments exported:

![image](https://user-images.githubusercontent.com/7717432/127786613-947208f4-6ac3-49a4-b85c-8731d1b25a6c.png)
![image](https://user-images.githubusercontent.com/7717432/127786671-8061d4da-88e0-4b80-ada5-4fe9d7cb0610.png)
