### ISSUE TITLE
Channel ID filter

### ISSUE THREAD

**Issue by John9593** [mattwright324/youtube-comment-suite#36]
Would it be possible please to add a way to sort and search via channel ID, sometimes names are very similar and using the 'name like' function brings up others, also sometimes people change their channel names and the changes don't always reflect in the program.

**Comment by mattwright324** [comment]
This seems like a good feature and fairly easy to implement. I have something similar with video ids on the video select modal when comment searching.

**Comment by John9593** [comment]
Thank you

**Comment by mattwright324** [comment]
I will have this out soon in the next release, 1.4.3. I have it so you can paste a channel id in the name search field and all comments whose channel id match will show. Similarly have the same thing for comment ids and the comment text search field. I also added new context menu options to copy comment and channel ids from comments in the list.
