### ISSUE TITLE
Toggle duplicate filter on comment context menu copy options

### ISSUE THREAD

**Issue by John9593** [mattwright324/youtube-comment-suite#37]
When selecting lots of channel names, right clicking, copying the names it removes the duplicates - is there a way to turn this off however so it copies every name? 

Thanks

**Comment by mattwright324** [comment]
Why would you want to include duplicates?

**Comment by John9593** [comment]
Because I copy lists out, so I might select 50 comments, and want the 50 channel names and links but then when I paste them of course if there are any duplicates removed they don't match up

**Comment by mattwright324** [comment]
I could make this a settings option where duplicates are removed by default but can be turned off.

**Comment by mattwright324** [comment]
I have this implemented as a new settings option you can turn off but will be enabled by default. `Filter duplicates on comment context copy options`. It will be out in the next release, 1.4.3.
