### ISSUE TITLE
Deleting item does not delete comments

### ISSUE THREAD

**Issue by John9593** [mattwright324/youtube-comment-suite#38]
I deleted a channel from the program, and it removed it from the group - however, the videos are still there as are the comments.
The video can be selected within the group still and all comments still appear.
I've tried cleaning the DB but it doesn't seem to get rid of them, also have tried deleting an entire group which does remove them.

**Comment by mattwright324** [comment]
When deleting it only deletes unique unlinked items. Did you have a playlist that may have contained the same videos? or another group with that same channel still on it?
Another potential reason, did you have two instances of the program running? One will lock the file meaning the other couldn't make updates to the db.

**Comment by John9593** [comment]
No, I've checked the entire group list (on all groups) via SQL and the reference to the channel doesn't exist, so it's been removed from the groups. (I need to do a refresh to test whether any new comments I removed appear).
Definitely no playlist (have none added), but video ID's appear under the video table, and the comments still link.
I haven't run two instances.

**Comment by John9593** [comment]
I've confirmed after refreshing the data, that it still grabs the new comments (and new videos) from the channel despite it not being in the group, and not referenced within group_gitem

**Comment by mattwright324** [comment]
How large is the sqlite file, would you be able to zip that along with the contents of the logs folder?

**Comment by mattwright324** [comment]
Haven't been able to reproduce and deleting a channel from a group correctly deletes related comments, channels, and other rows from other tables.
