### ISSUE TITLE
Jar file won't open

### ISSUE THREAD

**Issue by scriptomania** [mattwright324/youtube-comment-suite#39]
The youtube-comment-suite-1.4.2 jar file won't open when double clicked on.

**Comment by mattwright324** [comment]
Java version, OS?

**Comment by mattwright324** [comment]
That sounds like it should work fine. What anti virus are you doing?

**Comment by scriptomania** [comment]
I've got avast and malwarebytes. Those shouldn't be affecting it. Strange..

**Comment by mattwright324** [comment]
Wouldn't expect them too but you never know. Check into both and see if you can find anything, otherwise is there a logs/ folder in the application folder and anything in it?

**Comment by dfisheritp** [comment]
Forgive me for being "basic." But I want to make sure that the jar file is being run correctly. You can either follow the directions for the "jar" fix that is commonly associated with MineCraft or run the application through the terminal / command / run.exe.
> java -jar path/to/file.jar

Problems that I'm having
Update your installation instructions to also include extracting the lib directory to the same location. =P

**Comment by mattwright324** [comment]
Including the `lib` folder alongside the jar is definitely important otherwise it won't run. I guess I had assumed that extracting all contents to a folder via the Extract menu item on a zip file as provided by Ubuntu and Windows would be most common.
