### ISSUE TITLE
Really needed addition to the application

### ISSUE THREAD

**Issue by Aasim-Awesome** [mattwright324/youtube-comment-suite#4]
Hey Matt,
First of all thanks for making this great app! It is literally the most convenient app out there.
But there is only one missing feature that would make this app excellent, and that is to make a new way to view comments by the video, what I mean is, now when you want to view the comments you either need to search for the specific comment or view the whole library.
**If there is a new menu that displays a video list and when you click that video the comments related to it would appear, that would be an amazing addition to the app!**

**thanks again for your work!**

**Comment by mattwright324** [comment]
Hi Aasim,

Thanks for the feedback! I had considered adding an option like this to search comments on a specific video before but faced the problem of a potentially massive list of videos to select from; some channels have thousands to tens of thousands of videos. Of course that is not the norm, many channels have less than a hundred to a few hundred videos published (still would be a pain to scroll and select from). At the time, this is why I had not added this feature.

A drop down similar to the group and group-item selection is not ideal for those situations. I'll look into this again and come up with a better solution -- I already have a couple ideas in mind that I would like to test out.

**Comment by mattwright324** [comment]
I'm not sure I understand. Do you mean add another section in `Manage Groups` to list the associated videos of group-item(s) in a similar fashion the videos are listed in the `About Videos` tab?

**Comment by Aasim-Awesome** [comment]
Not like that, what I meant is add another tab in the bar that contains the `search comments, manage groups and search YouTube` , a new tab that you can select your group, and select a channel and it will show the videos that belong to the selected channel in the same interface or similar to the videos in the `About Videos>Most popular videos` for example, and you will be able to click a video and the comments associated with the selected video will appear.

**Comment by mattwright324** [comment]
Okay, I think I understand now. One of my planned ideas is similar but would stay contained within the `Search Comments` tab. I am imagining some kind of popup/closable frame similar to the rest of the application where it will list but you can also filter, sort, and search through the videos. Access to it would be placed right below the group-item select box.

**Comment by Aasim-Awesome** [comment]
That is a pretty cool implementation.
Can't wait for it to be added!

**Comment by mattwright324** [comment]
6021431e8cfd7346842f667f3ee95d1d33582e23

**Comment by mattwright324** [comment]
Released v1.3.1 and you can download it [here](https://github.com/mattwright324/youtube-comment-suite/releases/tag/v1.3.1). You can now search and sort videos and select a specific one for comment searching. Other small changes can be read on the release page.
