### ISSUE TITLE
Running on mac

### ISSUE THREAD

**Issue by Chmm3** [mattwright324/youtube-comment-suite#42]
I have a windows 10 machine however I ran into the same issue so I feel as it is not the machine but I cannot find the proper jar to run? when I run from just any old file it says that it cannot find a main method.

**Comment by mattwright324** [comment]
What version(s) of Java do you have installed?

**Comment by Chmm3** [comment]
when I type [java --version] I get the output 
java 12.0.1 2019-04-16
Java(TM) SE Runtime Environment (build 12.0.1+12)
Java HotSpot(TM) 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)

**Comment by mattwright324** [comment]
That would be the problem, there are issues running it in versions 11 and up. I have more details in #6 but the recommended version is to use it in Java 8.

**Comment by Chmm3** [comment]
Sorry for pestering, but what wile should I run to start the program?

**Comment by mattwright324** [comment]
Assuming you meant `file`... you should be able to start it by double clicking the file `youtube-comment-suite.jar` but I'm not familiar with Mac and it may be different. Let me know if that works

**Comment by Chmm3** [comment]
Yes, I did mean file, sorry about that. I don't know if it is just my mac but I cannot for the life of me find the file `youtube-comment-suite.jar`.

**Comment by mattwright324** [comment]
What did you download? The zip file should be available in the releases section.

**Comment by Chmm3** [comment]
I downloaded the `.zip` but I thought I wanted to unzip the file, should I have done something different?

**Comment by mattwright324** [comment]
Yup, that is right but which zip? `Source code (zip)` which does not have the jar or `youtube-comment-suite-v1.4.2.zip` which does have the jar?

**Comment by Chmm3** [comment]
Yup, that was it. Thank you for helping fix my oversight.
