### ISSUE TITLE
can not find .jar file

### ISSUE THREAD

**Issue by mfarhan498** [mattwright324/youtube-comment-suite#44]
i just download it and i not found the main running .jar file

**Comment by bamtan** [comment]
https://github.com/mattwright324/youtube-comment-suite/issues/33#issuecomment-557544154
https://github.com/mattwright324/youtube-comment-suite/issues/42#issuecomment-590866106

**Comment by mattwright324** [comment]
Closing since there hasn't been any replies. Your linked comments should cover it, thanks @bamtan
