### ISSUE TITLE
Default and cancel behavior for modal buttons

### ISSUE THREAD

**Issue by dfisheritp** [mattwright324/youtube-comment-suite#49]
For small dialog boxes, add default button and cancel button.

**Comment by mattwright324** [comment]
Hi @dfisheritp, which modals are you referring to? Most of the small modals do have a default (colored) and cancel/close (standard silver/gray) buttons.

**Comment by dfisheritp** [comment]
Under Manage Groups
Add, Remove, Remove All item(s) does not have a cancel button set. While the buttons have a color changed set for them, I'm not receiving any kind of feedback from the program when I press Enter or Esc (or space bar when no adding items)
Refresh and Delete group windows also don't have any default or cancel button feature set.

For reference adding these attributes, cancelButton="true" defaultButton="true", to MGMVDeleteGroupModal.fxml will add in that functionality pretty quickly

**Comment by dfisheritp** [comment]
PS (default delete or quit buttons should typically always error on the side of caution and be the same as the "this was a mistake")

**Comment by mattwright324** [comment]
I see what you are saying now, I hadn't known those properties existed on the JavaFX Button and it would be pretty easy to add in.

https://docs.oracle.com/javase/8/javafx/api/javafx/scene/control/Button.html

**Comment by mattwright324** [comment]
Adding as a property on the buttons in the FXML files doesn't really work out too well but I was able to use those properties by setting them via Java instead and listening to changes in each modal's visible property. Seems to work pretty well, it will be out in the 1.4.3 release.
