### ISSUE TITLE
Replies in condensed export missing commentDate field

### ISSUE THREAD

**Issue by adsl3** [mattwright324/youtube-comment-suite#50]
Everything is ok in the app itself but when you export comments of a certain video, "commentDate" of replies are NOT getting exported. If you check out the threads you can clearly see the time underneath every reply but there is no such thing when you export them. Hope it's clear enough. In case it's still unclear, fetch a random video, look at its comments and then check its threads. You can see every comment and reply has a date of post. Now export it with Condensed mode and check the exported file again. You can see commentDate exists for the comment itself but its replies have no such things.
Can you fix this please?

Update:  Alright so I played around a little bit and the problem seems to be in export. I opened 'commentsuite.sqlite3' and everything was there as expected. But comment_date of replies seems to be missing from somewhere in the export process.

**Comment by mattwright324** [comment]
This looks to be an issue with just condensed mode, replies in flattened mode do have the commentDate in export output. This is very easy to fix.

**Comment by adsl3** [comment]
How may I have access to the fixed version? Are you going to release it as 1.4.3 or a single file as hotfix?
I really appreciate your hard work

**Comment by mattwright324** [comment]
It would be in a 1.4.3 release included with other general maintenance. Can't exactly say when but hopefully soon.

**Comment by mattwright324** [comment]
I have this fixed and it will be out in the next release, 1.4.3.
