### ISSUE TITLE
[Improvement] Ability to pause?

### ISSUE THREAD

**Issue by adsl3** [mattwright324/youtube-comment-suite#54]
So since many people are using your application and we see the error "quota exceeded" many times, I guess it would be awesome to add a Pause button beside Stop so that we can use our own API key, and then for instance pause the fetch process and wait until 00:00 pacific time that quota resets and then resume. So that it doesn't have to start over from first and do it all over again and check for newest comments. (which is a noticeable amount for videos with hundreds of thousands of comments.)
I myself really don't care about the new comments, I just want to reach the end as soon as possible, a pause/resume button would be nice for me. If anyone wants to like refresh the comments and see the new ones as well, they can simply just refresh it.
Hope I could explain it well

P.S:  The Pause button will save the nextPageToken (or idk, any other parameter that can identify its current position in comments) in its memory and in case of Resume, will start from it was paused (it will NOT check for newest comments again)

![2020-09-11 18_15_17-YouTube Comment Suite](https://user-images.githubusercontent.com/26360368/92933360-6b712580-f45b-11ea-9868-76e28463a3ed.png)

**Comment by mattwright324** [comment]
I'm a bit hesitant for this pause idea specifically. Though this suggestion and some of your comments bring a different idea.

Currently the refresh style is to grab everything regardless of circumstances which can be a bit extreme and probably contributes to a lot of the quota usage.

I could implement different refresh styles/modes where the default is lighter and smarter than the extreme current default. For example, possibly in this new mode it would be configurable such that it would only grab comments on videos that haven't been refreshed fully in _x_ amount of days/hours and/or video statistics show the comment count has increased _y_ amount more than the last time it was refreshed. 

It would be a bit in spirit of the #43 blacklisting idea but going about it in a different way.

The problem with saving page tokens is that they do expire but I don't know how long they last. The YouTube API docs don't exactly specify other than saying they expire.

**Comment by adsl3** [comment]
Different refresh styles/modes sounds brilliant! It will definitely use less quota which is exactly what I want. Really appreciate it

**Comment by mattwright324** [comment]
I have implemented refresh styles and some customization in the `develop` branch and will be out in the next release.

![image](https://user-images.githubusercontent.com/7717432/105612935-50111200-5d8d-11eb-8df1-07fcd600db64.png)
![image](https://user-images.githubusercontent.com/7717432/105612921-3c65ab80-5d8d-11eb-92ad-2d76b3a4d7d6.png)
![image](https://user-images.githubusercontent.com/7717432/105612930-48516d80-5d8d-11eb-8729-f8634b97ad3e.png)
