### ISSUE TITLE
Add account and API key are not working

### ISSUE THREAD

**Issue by fabiomb** [mattwright324/youtube-comment-suite#56]
Hi there, 

i downloaded the app today and installed Java 8 from the default download site (Oracle) you have linked. The app starts fine but i can't add a Google Account.

It opens the screen with the login but the "next" button does nothing, probably a Javascript error but i have no access to console or anything so i can't know exactly what is happening.

Next i tried adding a new API Key, but even this gives a 403 error (as i saw in the Google API console) 
youtube.api.v3.V3DataVideoService.List this service is accesed but with no results when i search

Java version: 8.261
I am running this from Windows 10

**Comment by fabiomb** [comment]
changed the API key and that part is working now, but not the login :(

**Comment by mattwright324** [comment]
Hey @fabiomb,

I just tried to add my own Google account in the app and it worked fine for me. I too am using Java 8 u261. If the problem is visual could you give a screenshot? Could you also look in the `logs/` folder and send any errors or exceptions you may see?
