### ISSUE TITLE
Not able to run

### ISSUE THREAD

**Issue by ajithex** [mattwright324/youtube-comment-suite#57]
Your work seems great.
I am using Ubuntu and am not good in java, but I follow all your step but dont know how to run. Please Guide. Thanks in advance.

**Comment by mattwright324** [comment]
Hi @ajithex,

Which Ubuntu version are you running? 

My guide to install and run for several Ubuntu versions is here on this wiki page, [Installation Ubuntu 16 17 18 19 20](https://github.com/mattwright324/youtube-comment-suite/wiki/Installation---Ubuntu-16-17-18-19-20). You followed these steps?

**Comment by ajithex** [comment]
Hi @mattwright324 
I used Ubuntu18, I followed your instruction all seems to be install but I dont know how to start the program, I am not familiar with Java. Help me out.

**Comment by mattwright324** [comment]
If you correctly installed Java 8 and JavaFX 8 in my steps then the End section tells you how to start the program by either using the `chmod` command to enable double click or just by running the `java` command.

**Comment by Board3659** [comment]
I have java 8 and I am trying to find youtube-comment-suite-v#.#.#.jar, but can't find it. Also don't know where jib is.

**Comment by mattwright324** [comment]
@Board3659 Check these out and see if they help at all
https://github.com/mattwright324/youtube-comment-suite/issues/33#issuecomment-557544154
https://github.com/mattwright324/youtube-comment-suite/issues/42#issuecomment-590866106

**Comment by Board3659** [comment]
Thanks, I will try and if I have trouble I might comment again.

**Comment by Board3659** [comment]
Can you tell me the files I have to press to get to youtube-comment-suite-v#.#.#.jar?

**Comment by mattwright324** [comment]
Did you click and read my linked comments? Did you download the source code zip or the youtube-comment-suite-v1.4.3.zip? Unzip the youtube-comment-suite-v#.#.#.zip and the jar will be there.

**Comment by Board3659** [comment]
The youtube-comment-suite-v1.4.3.zip

**Comment by mattwright324** [comment]
That is the right one, unzip that and the jar and require lib folder are inside. Assuming you are on windows, you can right click the zip and click "Extract all..."

**Comment by Board3659** [comment]
I extracted them all, what do I do to run it? (Sorry if I am bothering you)

**Comment by mattwright324** [comment]
In what you extracted, double click the youtube-comment-suite-1.4.3.jar to run it
