### ISSUE TITLE
Update README: Install with Java SDK >11 and JavaFX

### ISSUE THREAD

**Issue by Gorrrg** [mattwright324/youtube-comment-suite#59]
I tested youtube-comment-suite with the latest version of Java SDK which is 15.0.1 and the now seperate JavaFX and it still works a treat. However it's a bit tricky for Java beginners to run the program with anything above version 11 (since then JavaFX is no longer integrated with Java). So I'd suggest to add a few lines on how to set it up.

1. Download JavaFX **SDK** from [here](https://gluonhq.com/products/javafx/). Choose the version that corresponds to your architecture and Java SDK version.
2. Unzip the JavaFX archive into your prefered location (on Windows x64, it's usually "C:\Program Files\Java\")
3. Open a command prompt in the directory where you unzipped youtube-comment-suite and use this command line to launch it (on Windows x64): **javaw.exe --module-path "C:\Program Files\Java\javafx-sdk-15.0.1\lib" --add-modules ALL-MODULE-PATH -jar youtube-comment-suite-1.4.3.jar**

Slightly change procedures for Linux and MacOS...

Why is this important? Some people might not want to install Java RE or SDK 8 and I also noticed that when Windows is scaled to something different than 100% your app does not look right with Java 8 but it does with Java 15.

**Comment by mattwright324** [comment]
I've created a wiki page https://github.com/mattwright324/youtube-comment-suite/wiki/Installation---Java-11 and will be linking it in the README.md in the next release.
