### ISSUE TITLE
Not being able to run Jar file

### ISSUE THREAD

**Issue by ultramyslixs** [mattwright324/youtube-comment-suite#62]
For some reason, running the youtube-comment-suite-1.4.3.jar file stopped working. I have tried running it from the command line using `java -jar youtube-comment-suite-1.4.3.jar` and `javaw -jar youtube-comment-suite-1.4.3.jar` and received the error `Error: Unable to access jarfile youtube-comment-suite-1.4.3`. I then tried running the jar file with the java.exe and the javaw.exe file located in `C:\Program Files\Java\jdk-14.0.1\bin`, which did not work either. Are there any fixes to this? Tried reinstalling Java and restarting my computer with no success.

**Comment by mattwright324** [comment]
Hey @ultramyslixs 

Well the issue appears to be the Java version, did you update it recently? It seems that you have Java 14 based on that JDK path. The issue with Java 11 and newer is that JavaFX is no longer bundled and the GUI for YouTube Comment Suite is built with JavaFX.

There is a way to get it running in newer JDKs if you take a look at #59. However, you could also downgrade your JDK to Java 8.

**Comment by ultramyslixs** [comment]
Ok thanks for informing me about this. I actually had installed the latest version of Java just a couple days ago, which is why it stopped working. I reinstalled Java 8 and everything works fine. Thank you!
