### ISSUE TITLE
Deleting the default group causes it to duplicate

### ISSUE THREAD

**Issue by kacper1112** [mattwright324/youtube-comment-suite#65]
It is possible to delete the default group in the application. After doing that, a second default group appears in the groups list. They both appear to be referencing the same group though. Adding and deleting content from one affects the other in the same way. 
![2default](https://user-images.githubusercontent.com/36137483/104068050-1a7aff00-51b9-11eb-8229-756a55b8c18b.png)

The behavior is quite similar to #63 , they may have similar causes? 

I think it would be a good idea to disable the 'delete group' button for the default group.

Platform: Windows 10
Java: 1.8.0_271 (Oracle)

Ran both using the release 1.4.3 jar file and compiled from source myself.

**Comment by mattwright324** [comment]
I am able to reproduce, looking into this now. Thanks @kacper1112

**Comment by mattwright324** [comment]
I have this fixed in a commit to the develop branch b56f2e334b139367a2d1f4c08ca080e1722cf8ef and will be in the next release.
