### ISSUE TITLE
Group selection list is not updated after group name change

### ISSUE THREAD

**Issue by kacper1112** [mattwright324/youtube-comment-suite#66]
This one is a little picky :)
Here I've created a group called 'OldGroupName':
![oldgroupname](https://user-images.githubusercontent.com/36137483/104070189-29fb4780-51bb-11eb-938e-691e689fedc8.PNG)
After changing its name, in the group selection list, we still see the old name.
![newgroupname](https://user-images.githubusercontent.com/36137483/104070246-4f885100-51bb-11eb-988c-02b90a63e654.PNG)
Expanding the list causes a state, where both new and old names are visible.
![newgroupnamelist](https://user-images.githubusercontent.com/36137483/104070318-75155a80-51bb-11eb-8255-d2cd4a05e1a8.PNG)
After switching to another group and back, the list is now properly updated.
![newgroupnameworking](https://user-images.githubusercontent.com/36137483/104070429-b574d880-51bb-11eb-8695-f749af1b4301.PNG)

Platform: Windows 10
Java: 1.8.0_271 (Oracle)

Ran both using the release 1.4.3 jar file and compiled from source myself.

**Comment by mattwright324** [comment]
Yup, I've known about this one for a long time and created issue #7, tried to fix it but couldn't at the time.

**Comment by kacper1112** [comment]
Oh, sorry, did not notice that one.

**Comment by mattwright324** [comment]
Giving it another go, I was able to solve it. Have to set the select box to a new empty list then back to the original list for it to update the new text.

I have this fixed in a commit to the develop branch b56f2e334b139367a2d1f4c08ca080e1722cf8ef and will be in the next release.
