### ISSUE TITLE
Suggestion: after creating a group, the last refresh date points to 01.01.1970 - change to 'Never refreshed'

### ISSUE THREAD

**Issue by kacper1112** [mattwright324/youtube-comment-suite#68]
As above, the default 'last refresh' time is set to lowest possible value. It would be more readable for users to have it say something along the lines of 'Never refreshed', 'Please refresh first'.

**Comment by mattwright324** [comment]
https://github.com/mattwright324/youtube-comment-suite/blob/aeabc826d72c833a279c8cf16ec63037e9422b5c/src/main/java/io/mattw/youtube/commentsuite/fxml/ManageGroupsManager.java#L441-L449

Actually looks like I had it setup to display "Never refreshed" at one point but that stopped working and I forgot it was supposed to do that. I'll look into getting it working again, thanks!

**Comment by mattwright324** [comment]
I have this fixed in a commit to the develop branch e0c77bcd922f3d87a7cb859fcb536183edb10ef6 and will be in the next release.
