### ISSUE TITLE
Possibility to search for empty strings

### ISSUE THREAD

**Issue by kacper1112** [mattwright324/youtube-comment-suite#69]
I don't know whether to classify this as a bug or a feature. It is possible to search for content without entering any input to the search box. YouTube website does not allow that. For me, the most general 'empty' search returns:
![emptysearch](https://user-images.githubusercontent.com/36137483/104072957-5dd96b80-51c1-11eb-9c9e-2d2023bb367c.PNG)
However, when I try to sort the results by views, it does not return anything.
![emptysearchsort](https://user-images.githubusercontent.com/36137483/104073041-90836400-51c1-11eb-91b4-29b7f696d0c4.PNG)

Platform: Windows 10
Java: 1.8.0_271 (Oracle)

Ran both using the release 1.4.3 jar file and compiled from source myself.

**Comment by kacper1112** [comment]
Sorting by views seems to be a separate issue. I've created a new one here: #70

**Comment by mattwright324** [comment]
The YouTube API allows for this to happen and would be preferred when using the location search if you don't have keywords in mind. I could make it not search when the type is Normal and its empty but not really sure.
