### ISSUE TITLE
Export Comments to Excel

### ISSUE THREAD

**Issue by kostasall12** [mattwright324/youtube-comment-suite#75]
Hello .

 Is there a way to export all youtube comments to word or excel file?

**Comment by mattwright324** [comment]
Duplicate of #35 

This is on my list of things to do, currently the only export method is JSON. It definitely would be useful to have an export to CSV format and possibly other options for the export.

**Comment by mattwright324** [comment]
I have a working version of CSV export and it will be out in the next release.
