### ISSUE TITLE
Export to Spreadsheet

### ISSUE THREAD

**Issue by ae5960e8-a6fc-491f-b252-898ecf59af95** [mattwright324/youtube-comment-suite#83]
Please consider adding an option to export all comments from a YouTube video/YouTube channel to a spreadsheet document.

**Comment by Himusaki** [comment]
I want the same feature 
Tired of JSON.

@mattwright324 Plz help us again.

Thanks alot for your hard work

**Comment by Himusaki** [comment]
@mattwright324 please at least reply.

**Comment by mattwright324** [comment]
Duplicate of #35

Closing this and will update progress on the other issue. I will note that I am working on this right now, there will be an option to export as JSON or CSV soon.

**Comment by mattwright324** [comment]
I have a working version of CSV export and it will be out in the next release.
