### ISSUE TITLE
Does nothing when opening jar

### ISSUE THREAD

**Issue by myangelaku** [mattwright324/youtube-comment-suite#89]
Am on Java8 Windows

**Comment by mattwright324** [comment]
Hey @myangelaku 

To double check, if you open command prompt and type `java -version` what does it say?

Also in command prompt, cd to the application folder and type `java -jar youtube-comment-suite-1.4.7.jar` and does it give an error?

**Comment by myangelaku** [comment]
Hmmm, apparently not on Java 8 after all, even though I am?

```
E:\youtube-comment-suite-v1.4.7\lib>java --version
java 16.0.1 2021-04-20
Java(TM) SE Runtime Environment (build 16.0.1+9-24)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)

E:\youtube-comment-suite-v1.4.7\lib>java -jar youtube-comment-suite-1.4.7.jar
Error: Could not find or load main class io.mattw.youtube.commentsuite.CommentSuite
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application
```

![ApplicationFrameHost_iFg5ol7MXf](https://user-images.githubusercontent.com/28674643/129140934-cb3d5b3e-784c-4378-b86c-d9e841adefd2.png)

**Comment by myangelaku** [comment]
Alright, fixed my Java installation, and it works now.
