### ISSUE TITLE
JVM crash on exit

### ISSUE THREAD

**Issue by bernard01** [mattwright324/youtube-comment-suite#94]
It appears that the exit button of the application calls System.exit() without waiting for running threads. I had multiple JVM crashes each time when I closed the application. Perhaps some database query or something else was still running. I finally got confirmation of this when I realized that the configuration got corrupted, reverting to the factory supplied API key. I could not detect any database corruption. I did not look at the log at the time.

**Comment by mattwright324** [comment]
Credentials, api keys, and other user preferences are stored in the `commentsuite.json` file, not the database. Could take a look at that if something got messed up if it was saving/writing to that file.

At the moment the application doesn't have a 'run in background' feature besides just minimizing the application. I assumed if you hit the X, you want it to stop everything. I haven't seen it happen but it sounds plausible for exiting the application especially during a larger refresh to crash/hs_err_pid.
