### ISSUE TITLE
SocketTimeout  Error

### ISSUE THREAD

**Issue by ElonMusked** [mattwright324/youtube-comment-suite#96]
Hi, sometimes when I'm scraping comments, I get this error after a while. And the worst part is, it hits 5/5 max retry after some time and program stops working. And I have to start the whole process from first again...

![err](https://user-images.githubusercontent.com/26360368/136569373-c23f2af8-2c70-42fd-8f8e-cdeb0d86e3d1.png)

Is there anyway to fix this? Or if you don't know what's going on, is there anyway I can increase that 5 max tries to a bigger number like 1,000 or something?

**Comment by mattwright324** [comment]
Hi @ElonMusked 

There currently isn't a way to increase the max retry count but that could be a good idea for more settings/customization.

What is the quality of your internet? download speed, over ethernet, over wifi? are there any other things downloading on your device or elsewhere on your network (windows updates, game updates, netflix...) that could be degrading your local internet?

**Comment by mattwright324** [comment]
Are you using a VPN at all? There was an issue #78 that I didn't get to verify but sounds like may cause connection issues in a Java application.

**Comment by ElonMusked** [comment]
Yeah sure, here is the video:
https://www.youtube.com/watch?v=jNQXAC9IVRw

So to answer your questions, I calculated everything:

Started at **04:20**
First error at **04:22**   _~25,000 comments_
Second error at **04:46**   _~325,000 comments_

I created this topic at 05:26
Third error at **05:27**   _~837,500 comments_

But no error since then, so basically from 837k till 2.5m no error. Now another thing to note is that, this time for [1/5 ]and [2/5] error, program was minimized and I had my vps closed (not shutdown). But [3/5] was when vps was open BUT program still minimized.
The other two times that program failed at 3m and 1.2m, I was asleep and your program was doing it it again in minimized mode. Idk it could be totally irrelevant to the issue but had to tell you every detail.

I didn't really have any problem with other videos because they didn't have as much comments. And also for this video I didn't take a look at comments when program failed cuz it was pointless anyway.

**Comment by mattwright324** [comment]
A single video with so many comments on it is certainly an edge case. I will try it out on my own and see what happens. It isn't the same thing but potential for something undocumented to be the case such as this issue where the YouTube API will stop returning videos from a playlist when you get to 20,000 videos. So you can't query for every video from a channel that has uploaded more than that.

https://github.com/mattwright324/youtube-metadata/wiki/YouTube-API-Notes#limit-for-playlistitemslist

**Comment by ElonMusked** [comment]
Mine is also over 5 millions now and no errors yet. But yeah, a retry configuration (both retries count and timeout maybe?) would be greatly appreciated cuz it shows its use when you have a weak internet connection that drops all the time or in my case having bad luck 😁
Thanks again for all your support

**Comment by ElonMusked** [comment]
Mission success!
Your program successfully dumped all those 11m comments. Nice job
