### ISSUE TITLE
Export results dumps everything

### ISSUE THREAD

**Issue by ElonMusked** [mattwright324/youtube-comment-suite#97]
Hi,

So I only wanted to dump around 50 comments out of 1,000 but your program keeps dumping all of them. This is exactly what I did (steps to reproduce):

Opened your program, went to **Search Comments** tab, on Type chose **Comments Only**, on Order By chose **Most Likes** and hit the Search button. It showed all of 1,000 comments. Then I clicked on first shown comment and shift clicked on 50th item to select all of them. So now 50 items are selected, right clicked and chose **Manage Tags**, then typed "**out**" in the box and clicked on **Add to selected**. Now 50 items have tag of **out**. Clicked on **finish**, and then on right side, clicked on "**Clear Results**", and on Has Tag(s) box, entered **out** so that only those 50 comments can be displayed. Then clicked on **Search**, took a few seconds and program showed exactly 50 comments. Then I clicked on **Export Results** and chose JSON on Export format and clicked on **Export**.

But now when I check the exported file, I still see all those 1,000 comments. Is it a bug or am I doing something wrong?

![YouTube Comment Suite](https://user-images.githubusercontent.com/26360368/137400749-2442e453-3d79-4f6c-af50-573a722a83fc.png)

**Comment by Spikesdev** [comment]
There is no "Export" button for me? How to enable it?
